### ISSUE TITLE
Nodatime compiled against raven 3.5

### ISSUE THREAD

**Issue by steinho** [mj1856/RavenDB-NodaTime#10]
Ravendb 3.5 is released. Will there be a version compiled against this release?

**Comment by mzoellner** [comment]
I created a PR for it (#11). Tested it locally with our codebase and RavenDB 3.5 and everything works as before.

**Comment by stevengopmo** [comment]
@mj1856 we would also like to see RavenDB 3.5.  Any chance the PR could be merged?  Maybe before 4.0 is released?

**Comment by iamisti** [comment]
I'm thinking of forking this repo and merging the PR. I will let you know if it's going to happen.
Does anybody know any alternative solution?
Is there any other repo which is maintained, not like this?

**Comment by mj1856** [comment]
Sorry for the delay on this.  PR #11 has been merged.  Will release shortly.

**Comment by mj1856** [comment]
Released v3.5.0.  Thanks again.

**Comment by stevengopmo** [comment]
I think that thanks goes to you sir.  Thank you for supporting this!
