### ISSUE TITLE
Support for NodaTime v2

### ISSUE THREAD

**Issue by CodingGorilla** [mj1856/RavenDB-NodaTime#12]
I was looking to use this for a project that I'm doing with NodaTime v2.0.2 and RavenDB v3.5 (latest stable) and I noticed this is based on NodaTime v1.x.  Are there plans to support NodaTime v2.x?

**Comment by mj1856** [comment]
Yes.  thanks for reminding me.  Will do this at some point.  It may require breaking changes.

**Comment by ryanheath** [comment]
#15 is a start to upgrade to nodatime v2.0 but some tests (5) are still failing.

**Comment by mj1856** [comment]
Published v3.6.0 to Nuget with support for NodaTime 2.  The tests that failed were removed, see #17.  Thanks.
