### ISSUE TITLE
DictionaryKeyConverter doesn't work for IDictionary

### ISSUE THREAD

**Issue by yurapara** [mj1856/RavenDB-NodaTime#4]
DictionaryKeyConverter CanConvert method checks if object type is derived from IDictionary that works OK for Dictionary but not for IDictionary itself.

**Comment by mj1856** [comment]
I can reproduce this, but at the moment I can't figure out a solution.  Will revisit.

**Comment by mj1856** [comment]
FYI - this is still an issue.  There is a failing unit test for it in the test suite.  If anyone wants to try to fix it, a PR is welcome.  Thanks.

**Comment by ryanheath** [comment]
#14 has a fix for this issue.
