### ISSUE TITLE
NuGet versions

### ISSUE THREAD

**Issue by mdocter** [mj1856/RavenDB-NodaTime#8]
Hi Matt,

Thank you for this great library!
I really would love to use it within a ASP.NET 5 web app, but I couldn't store Entities with LocalDate properties when using the most recent NodaTime and RavenDB.Client NuGet packages. Can't remember exactly, but it was something like: 'OffsetPattern.GeneralInvariantPattern' property does not exist. 
The NodaTime and RavenDB.Client versions I used were 2.0.0-alpha20150728 and 3.0.30026-Unstable. The problem I had was solved when I lowered the NodaTime and RavenDB.Client NuGet packages to version 1.3.0 and 3.0.3528, like you use in the Source Code.
Could you please update the project so it works with more recent NodaTime and RavenDB.Client NuGet packages? That would be really awesome and helpful.
I don't have enough knowledge in the Date/Time field to fork the project, fix it myself and send you a pull request. Please help.

Kind regards,

Maarten

**Comment by mj1856** [comment]
Thanks for the heads-up.  I'll test against the current versions and let you know what I find.

Be aware though that I don't intend to investigate ASP.NET 5 support (especially under .NET Core) until ASP.NET is RTM and the RavenDB Client is fully supporting it.

**Comment by mdocter** [comment]
Great! Thanks Matt! 
DNX only support is fine with me :-)

**Comment by mj1856** [comment]
Have you got Raven working under DNX yet?  I haven't tried myself.

**Comment by mdocter** [comment]
You mean the RavenDB server? Nope. Wouldn't know how to do that... 

I only tried the latest NuGet Client packages in a ASP.NET 5 web app (or [ASP.NET Core 1.](http://www.hanselman.com/blog/ASPNET5IsDeadIntroducingASPNETCore10AndNETCore10.aspx) as it's called now) against a local IIS hosted 3.0.30000 dev installation. 

Didn't try the 3.0.30037 build from last week yet either.

**Comment by mj1856** [comment]
Hey, sorry for the long delay.  I'm not doing much with RavenDB these days.

I just updated to support RavenDB 3.5.  It should work with the latest versions of everything now.

LMK if this is still a concern for you and I will reopen.  Thanks.
